export type ResourceType = "Food" | "Labor";

export type WorkerKind = "Farmer" | "Builder";

export interface CardDefinition {
  kind: WorkerKind;
  generates: ResourceType;
  amount: number;
  image: string;
}

export interface CardInstance {
  instanceId: string;
  kind: WorkerKind;
  tapped: boolean;
}

/**
 * v0 deviates from the design docs' rough turn-order guess
 * (Untap -> Upkeep -> Main -> Warfare -> End): Upkeep needs Food, but Food
 * is only generated by tapping Workers in Main. So here Main comes before
 * Upkeep (generate resources, then spend them), and Warfare comes after
 * Upkeep as a stub (no opponent modeled yet). Untap is instantaneous (no
 * choices) and folded into the End -> Draw transition rather than being
 * its own UI phase.
 *
 * "mulligan" is a pregame phase, not part of the turn cycle: it happens
 * before turn 1's Draw phase, and never recurs once the player is
 * satisfied and moves on. The player may repeat it (discard the whole
 * hand, redraw one fewer card each time) until only 1 card is left.
 */
export type Phase = "mulligan" | "draw" | "main" | "upkeep" | "warfare" | "end";

export interface PlayerState {
  deck: CardInstance[];
  hand: CardInstance[];
  lane: CardInstance[];
  graveyard: CardInstance[];
  resources: Record<ResourceType, number>;
  hasPlacedWorkerThisTurn: boolean;
}

export interface GameState {
  turn: number;
  phase: Phase;
  player: PlayerState;
  /** Food deficit still needing sacrifices this upkeep, if any. */
  pendingSacrifices: number;
  log: string[];
  gameOver: boolean;
}
