export type ResourceType = "Food" | "Labor";

/**
 * A card in play. `defId` references a CardDefinition in
 * game/components/registry.ts — what the card actually does lives there,
 * as a bag of components, not here. See game/components/types.ts.
 */
export interface CardInstance {
  instanceId: string;
  defId: string;
  tapped: boolean;
  /**
   * Cards attached to this one — e.g. a Draft Order (see Rules/Draft
   * Ability.md and Concepts/Orders.md), which stays behind its target
   * Worker rather than resolving once and going to the graveyard. Each
   * attachment is a full CardInstance with its own defId/component bag,
   * read generically by systems (see components/queries.ts's
   * hasWarfare/resourceGeneratedBy) — nothing here or in those systems is
   * special-cased to "the Draft card" by name, so a future attaching card
   * with different components (or a future card that detaches one) is
   * just more data, not a new code path.
   *
   * No per-card counters (see Concepts/Workers.md's "no per-card
   * counters" principle) — an attachment is either present or it isn't;
   * quantity/strength lives on the attachment's own printed components,
   * same as everything else in this game. Stays with its host through
   * everything, including combat: if the host is destroyed, its
   * attachments go to the graveyard as part of it (see phases/warfare.ts's
   * destroyFront) — nothing detaches an attachment yet.
   */
  attachments: CardInstance[];
}

/**
 * Every phase this game can be in. Each one is defined as its own module
 * under game/phases/ (name, label, and rules all in one place), and
 * game/phases/index.ts's TURN_PHASES array lists which of them are
 * actually active in the turn loop — comment a phase's entry out of that
 * array and it's fully disabled, nothing else to touch.
 *
 * v0 deviates from the design docs' rough turn-order guess
 * (Untap -> Upkeep -> Main -> Warfare -> End) in one place: Upkeep needs
 * Food, but Food is only generated by tapping Workers in Main. So here
 * Main comes before Upkeep (generate resources, then spend them) — see
 * Rules/On Player Phases.md's "Why Main comes before Upkeep". Untap is
 * genuinely its own phase (first in TURN_PHASES, see phases/untap.ts) —
 * an earlier version folded it into the End -> Draw transition instead,
 * which was a real bug (see Rules/On Player Phases.md's correction
 * section): that untapped a side's own cards before the *other* side's
 * turn even happened, erasing tapping's whole downside.
 *
 * "coinToss" and "mulligan" are pregame phases, not part of the turn
 * cycle: coinToss reveals who goes first (already decided at setupGame,
 * see firstSide below — this phase is just the on-screen reveal of it),
 * then hands off to mulligan, which happens before turn 1's Draw phase
 * and never recurs once the player is satisfied and moves on. The player
 * may repeat mulligan (discard the whole hand, redraw one fewer card each
 * time) until only 1 card is left.
 */
export type Phase = "coinToss" | "mulligan" | "untap" | "draw" | "main" | "upkeep" | "warfare" | "end";

/** Whose turn it is. Turns alternate — see phases/end.ts. */
export type Side = "player" | "opponent";

/** How the opponent plays (see game/ai.ts's AI_POLICIES) — chosen once at
 *  the main menu and fixed for the whole game (see setup.ts and
 *  RESTART's own handling in phases/index.ts). "dumb" is deliberately
 *  named for what it is: the original, single-strategy opponent this game
 *  shipped with before difficulty levels existed, kept unchanged as its
 *  own selectable level rather than folded into "easy". */
export type Difficulty = "dumb" | "easy" | "normal" | "hard";

export interface PlayerState {
  deck: CardInstance[];
  hand: CardInstance[];
  lane: CardInstance[];
  graveyard: CardInstance[];
  resources: Record<ResourceType, number>;
  hasPlacedWorkerThisTurn: boolean;
  /** One DRAFT per turn, same budget shape as hasPlacedWorkerThisTurn —
   *  see Rules/Draft Ability.md's open question about frequency; this is
   *  the default chosen until a card says otherwise. */
  hasDraftedThisTurn: boolean;
}

/**
 * Rule-level toggles a future card/ability can flip on, rather than special-
 * casing its effect into the reducer per card. See design/Rules/Placement
 * Modifiers.md in the Obsidian vault for the game-design side of this.
 */
export interface GameModifiers {
  /** Lets the player choose the lane index when placing a worker, instead
   *  of it always going to the back (see PLACE_WORKER's `index`). */
  freeWorkerPlacement: boolean;
}

export interface GameState {
  turn: number;
  phase: Phase;
  /** Whose turn is currently resolving — see game/helpers.ts's
   *  activePlayerState/withActivePlayerState, which every phase uses
   *  instead of hardcoding `player`. */
  activeSide: Side;
  /** Decided once by a coin toss at game start (see setupGame) and never
   *  changes afterward — End phase (phases/end.ts) compares it against
   *  activeSide to know whether both sides have gone this round yet. */
  firstSide: Side;
  modifiers: GameModifiers;
  player: PlayerState;
  /**
   * The opponent's board, mirrored on the other side of the table — a
   * real, independently-dealt PlayerState (their own deck, their own
   * starting hand), not placeholder data. Takes real, full turns just
   * like the player (see game/ai.ts for its Main-phase decisions, and
   * activeSide above for how turns alternate) — mulligan is the one
   * exception, staying player-only since it's a pregame step, not part
   * of the turn loop.
   */
  opponent: PlayerState;
  /** Chosen at the main menu, fixed for the game — see game/ai.ts. */
  difficulty: Difficulty;
  /** Food deficit still needing sacrifices this upkeep, if any. */
  pendingSacrifices: number;
  log: string[];
  gameOver: boolean;
}

/**
 * ADVANCE is the one generic "move on" action ("Next" button, "End Turn",
 * etc.) — what it actually does depends entirely on which phase is active,
 * since each phase interprets it for itself (see game/phases/*.ts). The
 * other actions are genuine player choices distinct from "move on".
 */
export type Action =
  | { type: "CONFIRM_COIN_TOSS" }
  | { type: "CONFIRM_MULLIGAN" }
  | { type: "FINISH_MULLIGAN" }
  | { type: "PLACE_WORKER"; instanceId: string; index?: number }
  | { type: "TAP_WORKER"; instanceId: string }
  /** Plays an attachable hand card (see Concepts/Orders.md and Rules/Draft
   *  Ability.md) at a target: `cardInstanceId` is the Order card itself
   *  (left hand, joins the target's attachments — not consumed to the
   *  graveyard), `targetInstanceId` is the untapped Worker it attaches to.
   *  A Worker never drafts itself. Named DRAFT rather than something more
   *  generic since Draft is still the only card that works this way; see
   *  components/queries.ts's isAttachable for the generic component any
   *  future Order card would share. */
  | { type: "DRAFT"; cardInstanceId: string; targetInstanceId: string }
  | { type: "SACRIFICE_WORKER"; instanceId: string }
  | { type: "RESOLVE_WARFARE" }
  | { type: "ADVANCE" }
  | { type: "RESTART" };
